name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: qwiklabs-gcp-03-efaa23e197d3

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag us-docker.pkg.dev/qwiklabs-gcp-03-efaa23e197d3/notely-ar-repo/notely:v1 .