name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: qwiklabs-gcp-04-0300f25ecc3d

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-docker.pkg.dev/qwiklabs-gcp-04-0300f25ecc3d/notely-ar-repo/notely:v1 \
            --region europe-west4 \
            --allow-unauthenticated \
            --project qwiklabs-gcp-04-0300f25ecc3d \
            --max-instances=4