name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: qwiklabs-gcp-00-42fd4b2413f1
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag us-docker.pkg.dev/qwiklabs-gcp-00-42fd4b2413f1/notely-ar-repo/notely:v1 .